package com.future.link.bulletin.model;

import com.future.link.bulletin.model.base.BaseBulletin;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Bulletin extends BaseBulletin<Bulletin> {
	public static final Bulletin dao = new Bulletin();
}
