package com.future.link.base.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMenu<M extends BaseMenu<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public void setRoute(java.lang.String route) {
		set("route", route);
	}

	public java.lang.String getRoute() {
		return get("route");
	}

	public void setPaths(java.lang.String paths) {
		set("paths", paths);
	}

	public java.lang.String getPaths() {
		return get("paths");
	}

	public void setParentId(java.lang.String parentId) {
		set("parentId", parentId);
	}

	public java.lang.String getParentId() {
		return get("parentId");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setOrderNum(java.lang.Integer orderNum) {
		set("orderNum", orderNum);
	}

	public java.lang.Integer getOrderNum() {
		return get("orderNum");
	}

	public void setIsLeaf(java.lang.Integer isLeaf) {
		set("isLeaf", isLeaf);
	}

	public java.lang.Integer getIsLeaf() {
		return get("isLeaf");
	}

}
