package com.future.link.goods.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGoods<M extends BaseGoods<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setShopId(java.lang.String shopId) {
		set("shopId", shopId);
	}

	public java.lang.String getShopId() {
		return get("shopId");
	}

	public void setCategoryId(java.lang.String categoryId) {
		set("categoryId", categoryId);
	}

	public java.lang.String getCategoryId() {
		return get("categoryId");
	}

	public void setCreateUser(java.lang.String createUser) {
		set("createUser", createUser);
	}

	public java.lang.String getCreateUser() {
		return get("createUser");
	}

	public void setSellStatus(java.lang.Integer sellStatus) {
		set("sellStatus", sellStatus);
	}

	public java.lang.Integer getSellStatus() {
		return get("sellStatus");
	}

	public void setShopPrice(java.lang.Double shopPrice) {
		set("shopPrice", shopPrice);
	}

	public java.lang.Double getShopPrice() {
		return get("shopPrice");
	}

	public void setTag(java.lang.String tag) {
		set("tag", tag);
	}

	public java.lang.String getTag() {
		return get("tag");
	}

	public void setCreateTime(java.lang.Long createTime) {
		set("createTime", createTime);
	}

	public java.lang.Long getCreateTime() {
		return get("createTime");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public void setUnit(java.lang.String unit) {
		set("unit", unit);
	}

	public java.lang.String getUnit() {
		return get("unit");
	}

	public void setImageUrl(java.lang.String imageUrl) {
		set("imageUrl", imageUrl);
	}

	public java.lang.String getImageUrl() {
		return get("imageUrl");
	}

	public void setQuantity(java.lang.Integer quantity) {
		set("quantity", quantity);
	}

	public java.lang.Integer getQuantity() {
		return get("quantity");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setDeleteTime(java.lang.Long deleteTime) {
		set("deleteTime", deleteTime);
	}

	public java.lang.Long getDeleteTime() {
		return get("deleteTime");
	}

	public void setUpdateTime(java.lang.Long updateTime) {
		set("updateTime", updateTime);
	}

	public java.lang.Long getUpdateTime() {
		return get("updateTime");
	}

	public void setRecordId(java.lang.String recordId) {
		set("recordId", recordId);
	}

	public java.lang.String getRecordId() {
		return get("recordId");
	}

	public void setDiscountedPrice(java.lang.Double discountedPrice) {
		set("discountedPrice", discountedPrice);
	}

	public java.lang.Double getDiscountedPrice() {
		return get("discountedPrice");
	}

}
