package com.future.link.base.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("base_menu", "id", Menu.class);
		arp.addMapping("base_menu_btn", "id", MenuBtn.class);
		arp.addMapping("base_role", "id", Role.class);
		arp.addMapping("base_role_menu", "id", RoleMenu.class);
		arp.addMapping("base_setting", "id", Setting.class);
		arp.addMapping("base_user_role", "id", UserRole.class);
	}
}

