package com.future.link.base.model;

import java.util.List;

import com.future.link.base.model.base.BaseMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Menu extends BaseMenu<Menu> {
	public static final Menu dao = new Menu();
	
	
	private List<Menu> subList;
	
	private List<MenuBtn> btnList;

	public List<Menu> getSubList() {
		return subList;
	}

	public void setSubList(List<Menu> subList) {
		this.put("subList", subList);
		this.subList = subList;
	}

	public List<MenuBtn> getBtnList() {
		return btnList;
	}

	public void setBtnList(List<MenuBtn> btnList) {
		this.put("btnList", btnList);
		this.btnList = btnList;
	}
}
