package com.future.link.base.model;

import com.future.link.base.model.base.BaseMenuBtn;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MenuBtn extends BaseMenuBtn<MenuBtn> {
	public static final MenuBtn dao = new MenuBtn();
}
