package com.future.link.base.model;

import com.future.link.base.model.base.BaseSetting;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Setting extends BaseSetting<Setting> {
	public static final Setting dao = new Setting();
}
