package com.future.link.consumer.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("consumer_consumer", "id", Consumer.class);
		arp.addMapping("consumer_salary", "id", Salary.class);
		arp.addMapping("consumer_withdraw", "id", Withdraw.class);
	}
}

