package com.future.link.consumer.model;

import com.future.link.consumer.model.base.BaseSalary;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Salary extends BaseSalary<Salary> {
	public static final Salary dao = new Salary();
}
