package com.future.link.consumer.model;

import com.future.link.consumer.model.base.BaseWithdraw;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Withdraw extends BaseWithdraw<Withdraw> {
	public static final Withdraw dao = new Withdraw();
}
