package com.future.link.consumer.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSalary<M extends BaseSalary<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setLayerAward(java.lang.Double layerAward) {
		set("layerAward", layerAward);
	}

	public java.lang.Double getLayerAward() {
		return get("layerAward");
	}

	public void setAAdvertisingaward(java.lang.Double aAdvertisingaward) {
		set("a_advertisingAward", aAdvertisingaward);
	}

	public java.lang.Double getAAdvertisingaward() {
		return get("a_advertisingAward");
	}

	public void setBAdvertisingaward(java.lang.Double bAdvertisingaward) {
		set("b_advertisingAward", bAdvertisingaward);
	}

	public java.lang.Double getBAdvertisingaward() {
		return get("b_advertisingAward");
	}

	public void setManagementFee(java.lang.Double managementFee) {
		set("managementFee", managementFee);
	}

	public java.lang.Double getManagementFee() {
		return get("managementFee");
	}

	public void setWithdrawalFee(java.lang.Double withdrawalFee) {
		set("withdrawalFee", withdrawalFee);
	}

	public java.lang.Double getWithdrawalFee() {
		return get("withdrawalFee");
	}

	public void setRealWage(java.lang.Double realWage) {
		set("realWage", realWage);
	}

	public java.lang.Double getRealWage() {
		return get("realWage");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("createDate", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("createDate");
	}

	public void setConsumerId(java.lang.String consumerId) {
		set("consumerId", consumerId);
	}

	public java.lang.String getConsumerId() {
		return get("consumerId");
	}

}
