package com.future.link.consumer.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseConsumer<M extends BaseConsumer<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setContactPerson(java.lang.String contactPerson) {
		set("contactPerson", contactPerson);
	}

	public java.lang.String getContactPerson() {
		return get("contactPerson");
	}

	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}

	public java.lang.String getPhone() {
		return get("phone");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}

	public java.lang.String getAddress() {
		return get("address");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public void setCreateTime(java.lang.Long createTime) {
		set("createTime", createTime);
	}

	public java.lang.Long getCreateTime() {
		return get("createTime");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setOrigin(java.lang.Integer origin) {
		set("origin", origin);
	}

	public java.lang.Integer getOrigin() {
		return get("origin");
	}

	public void setParentId(java.lang.String parentId) {
		set("parentId", parentId);
	}

	public java.lang.String getParentId() {
		return get("parentId");
	}

	public void setBankAccountName(java.lang.String bankAccountName) {
		set("bankAccountName", bankAccountName);
	}

	public java.lang.String getBankAccountName() {
		return get("bankAccountName");
	}

	public void setBankName(java.lang.String bankName) {
		set("bankName", bankName);
	}

	public java.lang.String getBankName() {
		return get("bankName");
	}

	public void setBankAddress(java.lang.String bankAddress) {
		set("bankAddress", bankAddress);
	}

	public java.lang.String getBankAddress() {
		return get("bankAddress");
	}

	public void setBankCard(java.lang.String bankCard) {
		set("bankCard", bankCard);
	}

	public java.lang.String getBankCard() {
		return get("bankCard");
	}

	public void setZipCode(java.lang.String zipCode) {
		set("zipCode", zipCode);
	}

	public java.lang.String getZipCode() {
		return get("zipCode");
	}

	public void setUserName(java.lang.String userName) {
		set("userName", userName);
	}

	public java.lang.String getUserName() {
		return get("userName");
	}

	public void setUserPwd(java.lang.String userPwd) {
		set("userPwd", userPwd);
	}

	public java.lang.String getUserPwd() {
		return get("userPwd");
	}

	public void setArea(java.lang.Integer area) {
		set("area", area);
	}

	public java.lang.Integer getArea() {
		return get("area");
	}

	public void setPrizeCoin(java.lang.Double prizeCoin) {
		set("prizeCoin", prizeCoin);
	}

	public java.lang.Double getPrizeCoin() {
		return get("prizeCoin");
	}

	public void setReferrerId(java.lang.String referrerId) {
		set("referrerId", referrerId);
	}

	public java.lang.String getReferrerId() {
		return get("referrerId");
	}

}
