package com.future.link.goods.model;

import java.util.List;

import com.future.link.goods.model.base.BaseGoods;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Goods extends BaseGoods<Goods> {
	public static final Goods dao = new Goods();
	
	/**
	 * 把imageUrl转化成绝对地址
	 */
	private String showUrl;
	
	/**
	 * 商品和店家内部分类的关联
	 */
	private List<GoodsCategoryRelation> categoryList;
	
	public String getShowUrl() {
		return showUrl;
	}

	public void setShowUrl(String showUrl) {
		this.put("showUrl", showUrl);
		this.showUrl = showUrl;
	}
	
	public List<GoodsCategoryRelation> getCategoryList() {
		return categoryList;
	}

	public void setCategoryList(List<GoodsCategoryRelation> categoryList) {
		this.put("categoryList", categoryList);
		this.categoryList = categoryList;
	}
}
