package com.future.link.goods.model;

import com.future.link.goods.model.base.BaseGoodsCategoryRelation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GoodsCategoryRelation extends BaseGoodsCategoryRelation<GoodsCategoryRelation> {
	public static final GoodsCategoryRelation dao = new GoodsCategoryRelation();
}
